-- DDL version: v2
-- Notes:
-- 1) PK uses BIGINT AUTO_INCREMENT
-- 2) Soft delete uses yn: N=active, Y=deleted
-- 3) All table names start with metadata_

CREATE TABLE `metadata_entity` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `code` VARCHAR(100) NOT NULL COMMENT '实体编码',
  `name` VARCHAR(255) NOT NULL COMMENT '实体名称（单数）',
  `name_plural` VARCHAR(255) DEFAULT NULL COMMENT '实体名称（复数）',
  `type` ENUM('Base','Hierarchy','ReferenceData','Relation','Archive') NOT NULL DEFAULT 'Base' COMMENT '实体类型',
  `icon_class` VARCHAR(100) DEFAULT NULL COMMENT '图标样式类',
  `color` VARCHAR(30) DEFAULT NULL COMMENT '显示颜色',
  `primary_entity_id` BIGINT DEFAULT NULL COMMENT '主实体ID（派生场景）',
  `customizable` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否可自定义',
  `layouts_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用布局',
  `tab_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否显示导航',
  `acl_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用权限控制',
  `importable` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否允许导入',
  `stream_disabled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否禁用动态流',
  `em_hidden` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否隐藏管理入口',
  `options_json` JSON DEFAULT NULL COMMENT '扩展配置JSON',
  `version` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否生效',
  `yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '软删除标记：N有效，Y删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by_id` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modified_by_id` BIGINT DEFAULT NULL COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_metadata_entity_code` (`code`,`yn`),
  KEY `idx_metadata_entity_type` (`type`,`yn`),
  KEY `idx_metadata_entity_primary` (`primary_entity_id`),
  CONSTRAINT `fk_metadata_entity_primary` FOREIGN KEY (`primary_entity_id`) REFERENCES `metadata_entity` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='实体元数据';

CREATE TABLE `metadata_group` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `entity_id` BIGINT NOT NULL COMMENT '所属实体ID',
  `code` VARCHAR(100) NOT NULL COMMENT '分组编码（实体内唯一）',
  `name` VARCHAR(255) NOT NULL COMMENT '分组名称',
  `description` VARCHAR(500) DEFAULT NULL COMMENT '分组说明',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序号',
  `is_system` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否系统内置',
  `version` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否生效',
  `yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '软删除标记：N有效，Y删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by_id` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modified_by_id` BIGINT DEFAULT NULL COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_metadata_group_entity_code` (`entity_id`,`code`,`yn`),
  UNIQUE KEY `uq_metadata_group_id_entity` (`id`,`entity_id`),
  KEY `idx_metadata_group_entity_sort` (`entity_id`,`sort_order`,`yn`),
  CONSTRAINT `fk_metadata_group_entity` FOREIGN KEY (`entity_id`) REFERENCES `metadata_entity` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='实体维度分组定义';

CREATE TABLE `metadata_field` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `entity_id` BIGINT NOT NULL COMMENT '所属实体ID',
  `group_id` BIGINT DEFAULT NULL COMMENT '所属分组ID（实体内）',
  `code` VARCHAR(100) NOT NULL COMMENT '字段编码（实体内唯一）',
  `name` VARCHAR(255) NOT NULL COMMENT '字段名称',
  `field_type` VARCHAR(50) NOT NULL COMMENT '字段类型',
  `relation_type` ENUM('oneToOne','oneToMany','manyToOne','manyToMany') DEFAULT NULL COMMENT '关系类型',
  `foreign_entity_id` BIGINT DEFAULT NULL COMMENT '关联实体ID',
  `foreign_code` VARCHAR(100) DEFAULT NULL COMMENT '关联字段编码',
  `required_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否必填',
  `read_only_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否只读',
  `is_multilang` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否多语言',
  `customizable` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否可自定义',
  `default_value_json` JSON DEFAULT NULL COMMENT '默认值JSON',
  `options_json` JSON DEFAULT NULL COMMENT '选项配置JSON',
  `conditions_json` JSON DEFAULT NULL COMMENT '条件配置JSON',
  `params_json` JSON DEFAULT NULL COMMENT '参数配置JSON',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序号',
  `version` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否生效',
  `yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '软删除标记：N有效，Y删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by_id` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modified_by_id` BIGINT DEFAULT NULL COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_metadata_field_entity_code` (`entity_id`,`code`,`yn`),
  KEY `idx_metadata_field_type` (`field_type`,`yn`),
  KEY `idx_metadata_field_group` (`group_id`,`yn`),
  KEY `idx_metadata_field_foreign_entity` (`foreign_entity_id`),
  CONSTRAINT `fk_metadata_field_entity` FOREIGN KEY (`entity_id`) REFERENCES `metadata_entity` (`id`),
  CONSTRAINT `fk_metadata_field_foreign_entity` FOREIGN KEY (`foreign_entity_id`) REFERENCES `metadata_entity` (`id`),
  CONSTRAINT `fk_metadata_field_group_simple` FOREIGN KEY (`group_id`) REFERENCES `metadata_group` (`id`),
  CONSTRAINT `fk_metadata_field_group_entity` FOREIGN KEY (`group_id`,`entity_id`) REFERENCES `metadata_group` (`id`,`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='字段元数据';

CREATE TABLE `metadata_attribute` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `entity_id` BIGINT NOT NULL COMMENT '所属实体ID',
  `group_id` BIGINT DEFAULT NULL COMMENT '所属分组ID（实体内）',
  `code` VARCHAR(100) NOT NULL COMMENT '属性编码（实体内唯一）',
  `name` VARCHAR(255) NOT NULL COMMENT '属性名称',
  `attribute_type` VARCHAR(50) NOT NULL COMMENT '属性类型',
  `attribute_panel_id` BIGINT DEFAULT NULL COMMENT '属性面板ID',
  `extensible_enum_id` BIGINT DEFAULT NULL COMMENT '扩展枚举ID',
  `composite_attribute_id` BIGINT DEFAULT NULL COMMENT '父复合属性ID',
  `is_multilang` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否多语言',
  `required_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否必填',
  `read_only_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否只读',
  `data_json` JSON DEFAULT NULL COMMENT '动态数据JSON',
  `params_json` JSON DEFAULT NULL COMMENT '参数配置JSON',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序号',
  `version` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否生效',
  `yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '软删除标记：N有效，Y删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by_id` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modified_by_id` BIGINT DEFAULT NULL COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_metadata_attribute_entity_code` (`entity_id`,`code`,`yn`),
  KEY `idx_metadata_attribute_type` (`attribute_type`,`yn`),
  KEY `idx_metadata_attribute_group` (`group_id`,`yn`),
  KEY `idx_metadata_attribute_composite` (`composite_attribute_id`,`yn`),
  CONSTRAINT `fk_metadata_attribute_entity` FOREIGN KEY (`entity_id`) REFERENCES `metadata_entity` (`id`),
  CONSTRAINT `fk_metadata_attribute_group_simple` FOREIGN KEY (`group_id`) REFERENCES `metadata_group` (`id`),
  CONSTRAINT `fk_metadata_attribute_group_entity` FOREIGN KEY (`group_id`,`entity_id`) REFERENCES `metadata_group` (`id`,`entity_id`),
  CONSTRAINT `fk_metadata_attribute_composite` FOREIGN KEY (`composite_attribute_id`) REFERENCES `metadata_attribute` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='属性元数据';

CREATE TABLE `metadata_client` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `scope_type` ENUM('ENTITY','APP','MODULE') NOT NULL DEFAULT 'ENTITY' COMMENT '作用域类型',
  `entity_id` BIGINT DEFAULT NULL COMMENT '实体ID（作用域为ENTITY时使用）',
  `scope_code` VARCHAR(100) NOT NULL COMMENT '作用域编码',
  `client_json` JSON NOT NULL COMMENT '客户端配置JSON',
  `version` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否生效',
  `yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '软删除标记：N有效，Y删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by_id` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modified_by_id` BIGINT DEFAULT NULL COMMENT '修改人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_metadata_client_scope` (`scope_type`,`scope_code`,`is_active`,`yn`),
  KEY `idx_metadata_client_entity` (`entity_id`,`yn`),
  CONSTRAINT `fk_metadata_client_entity` FOREIGN KEY (`entity_id`) REFERENCES `metadata_entity` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户端元数据';

CREATE TABLE `metadata_version` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `object_type` ENUM('ENTITY','GROUP','FIELD','ATTRIBUTE','CLIENT') NOT NULL COMMENT '对象类型',
  `object_id` BIGINT NOT NULL COMMENT '对象ID',
  `version` INT NOT NULL COMMENT '版本号',
  `operation` ENUM('INSERT','UPDATE','DELETE','PUBLISH','ROLLBACK') NOT NULL COMMENT '操作类型',
  `snapshot_json` JSON NOT NULL COMMENT '对象快照JSON',
  `comment` VARCHAR(500) DEFAULT NULL COMMENT '变更说明',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by_id` BIGINT DEFAULT NULL COMMENT '创建人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_metadata_version_obj_ver` (`object_type`,`object_id`,`version`),
  KEY `idx_metadata_version_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='统一版本记录';
